services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ../../../static_data:/var/lib/postgresql/static_data 
    ports: 
    - "5432:5432"
volumes:
  pgdata: